version: '3'
services:
  redis:
    image: "redis:5.0.5"
    ports:
      - "6379:6379"
  webfrontend:
    environment:
      - REDIS_HOST=redis
    image: "maguec/redis-streams-ws"
    links:
      - "redis:redis"
    ports:
      - "8080:8080"
